### ISSUE TITLE
Crashing on "BadDrawable"

### ISSUE THREAD

**Issue by mbardelmeijer** [pschultz/kiosk-browser#7]
Hi,

I'm currently using your script but i have a issue with it when it randomly crashes on a page (http://player.publish-engine.nl/status.php?status=123). I've tacked the crashing down to the "z-index: 100;" but it could happen on any page. Any idea what it can be? Thanks!

	(browser:15642): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-label-select-on-focus after class was initialised
	pi@raspberrypi ~/kiosk-browser $ ./browser http://player.publish-engine.nl/status.php?status=123
	 
	(browser:15652): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-label-select-on-focus after class was initialised
	pi@raspberrypi ~/kiosk-browser $ ./browser http://player.publish-engine.nl/status.php?status=123
	 
	(browser:15661): GLib-GObject-WARNING **: Attempt to add property GtkSettings::gtk-label-select-on-focus after class was initialised
	The program 'browser' received an X Window System error.
	This probably reflects a bug in the program.
	The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
	  (Details: serial 338 error_code 9 request_code 62 minor_code 0)
	  (Note to programmers: normally, X errors are reported asynchronously;
	   that is, you will receive the error a while after causing it.
	   To debug your program, run it with the --sync command line
	   option to change this behavior. You can then get a meaningful
	   backtrace from your debugger if you break on the gdk_x_error() function.)
	pi@raspberrypi ~/kiosk-browser $

**Comment by pschultz** [comment]
There is something wrong with the site it seems. It crashes my Android Browser too.

**Comment by pschultz** [comment]
I'm now back on my desktop and can see that the page is really simple. There can't see anything that should be able to crash a browser. Did you try removing the background-image yet?

**Comment by mbardelmeijer** [comment]
Thank you for checking. Am able to check it out on monday, will let you know the result. Seems like removing the "z-index" works, but had some issues with other sites as well. Will try to make a list with sites that crash it!

It should be running the latests WebKit right?

**Comment by mbardelmeijer** [comment]
Tried it with the libwebkit3 branch, and that seems to work.

**Comment by pschultz** [comment]
Glad to hear that.
